import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  foundationsSidebar:   [{type: 'autogenerated', dirName: '01-foundations'}],
  networkSidebar:       [{type: 'autogenerated', dirName: '02-network-security'}],
  systemSidebar:        [{type: 'autogenerated', dirName: '03-system-security'}],
  applicationSidebar:   [{type: 'autogenerated', dirName: '04-application-security'}],
  cloudSidebar:         [{type: 'autogenerated', dirName: '05-cloud-infrastructure'}],
  iamSidebar:           [{type: 'autogenerated', dirName: '06-identity-access-management'}],
  operationsSidebar:    [{type: 'autogenerated', dirName: '07-security-operations'}],
  offensiveSidebar:     [{type: 'autogenerated', dirName: '08-offensive-security'}],
  governanceSidebar:    [{type: 'autogenerated', dirName: '09-governance-compliance'}],
  emergingSidebar:      [{type: 'autogenerated', dirName: '10-emerging-security'}],
};

export default sidebars;
